version: '3.2'

services:
  adb-nginx:
    image: nginx:latest
    container_name: adb-nginx
    ports:
      - "8888:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html
    networks:
      - anet

  adb-db:
    image: mdillon/postgis
    container_name: adb-db
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - ./dbdata:/var/lib/postgresql/data
    ports:
      - '15432:5432'
    expose:
      - '5432'
    environment:
      POSTGRES_DB: adb
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    command: [ "postgres", "-c", "wal_level=logical" ]
    networks:
      - anet

networks:
  anet:
    driver: bridge
